services:
  # rails:
  #   build: .
  #   command: bundle exec rails s -p 3000 -b
  #   ports:
  #     - "18080:3000"
  #   stdin_open: true
  #   tty: true
  db:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - postgresql-local-data:/var/lib/postgresql/data

volumes:
  postgresql-local-data:
